// <auto-generated />
using System;
using Attorneys.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Attorneys.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621142055_AddMultiTenancy")]
    partial class AddMultiTenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseAccount", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNo")
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("TenantId", "CaseNo");

                    b.ToTable("case_accounts", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CaseNoId")
                        .HasColumnType("integer");

                    b.Property<string>("Ia")
                        .HasColumnType("text");

                    b.Property<string>("IaStage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PreviousDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseNo", "CaseNoId")
                        .IsUnique();

                    b.ToTable("case_details", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseDocument", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("FileId");

                    b.HasIndex("TenantId", "CaseNo");

                    b.ToTable("case_documents", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CasePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseNo");

                    b.ToTable("case_payments", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseType", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("CaseTypeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TenantId", "CaseTypeId");

                    b.ToTable("case_types", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.Court", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("CourtId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CourtCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("TenantId", "CourtId");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.LegalCase", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppearingFor")
                        .HasColumnType("text");

                    b.Property<string>("CaseTypeId")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("text");

                    b.Property<string>("CounselForOtherParty")
                        .HasColumnType("text");

                    b.Property<string>("CourtId")
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DateOfAppearance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfFiling")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherParty")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "CaseNo");

                    b.HasIndex("TenantId", "CaseTypeId");

                    b.HasIndex("TenantId", "CourtId");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseAccount", b =>
                {
                    b.HasOne("Attorneys.Domain.Entities.LegalCase", "Case")
                        .WithOne("Account")
                        .HasForeignKey("Attorneys.Domain.Entities.CaseAccount", "TenantId", "CaseNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseDetail", b =>
                {
                    b.HasOne("Attorneys.Domain.Entities.LegalCase", "Case")
                        .WithMany("Details")
                        .HasForeignKey("TenantId", "CaseNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseDocument", b =>
                {
                    b.HasOne("Attorneys.Domain.Entities.LegalCase", "Case")
                        .WithMany()
                        .HasForeignKey("TenantId", "CaseNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CasePayment", b =>
                {
                    b.HasOne("Attorneys.Domain.Entities.CaseAccount", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId", "CaseNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.LegalCase", b =>
                {
                    b.HasOne("Attorneys.Domain.Entities.CaseType", "CaseType")
                        .WithMany("Cases")
                        .HasForeignKey("TenantId", "CaseTypeId");

                    b.HasOne("Attorneys.Domain.Entities.Court", "Court")
                        .WithMany("Cases")
                        .HasForeignKey("TenantId", "CourtId");

                    b.Navigation("CaseType");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseAccount", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.CaseType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.Court", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Attorneys.Domain.Entities.LegalCase", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
