import { useEffect, useRef, useState } from "react";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  List,
  ListItem,
  Snackbar,
  Stack,
  Typography,
} from "@mui/material";
import {
  analyzeDocument,
  getAnalysis,
  retryAnalysis,
  setCachedDisplayStatus,
} from "../../services/documentAnalysisApi";
import {
  AI_DISPLAY_STATUS_CHIP_COLOR,
  AI_DISPLAY_STATUS_LABELS,
  DocumentAnalysisStatus,
  formatProcessedDate,
  mapAnalysisToDisplayStatus,
  type AiDisplayStatus,
  type DocumentAnalysisDto,
} from "../../types/documentAnalysis";

type DocumentAnalysisDialogProps = {
  open: boolean;
  fileId: number;
  fileName?: string;
  onClose: () => void;
  onStatusChange?: (fileId: number, status: AiDisplayStatus) => void;
};

type ViewState =
  | "loading"
  | "notFound"
  | "submitting"
  | "started"
  | "failed"
  | "inProgress"
  | "completed"
  | "error";

const resolveViewState = (analysis: DocumentAnalysisDto | null): ViewState => {
  if (!analysis) return "notFound";
  switch (analysis.status) {
    case DocumentAnalysisStatus.Completed:
      return "completed";
    case DocumentAnalysisStatus.Failed:
      return "failed";
    case DocumentAnalysisStatus.Pending:
    case DocumentAnalysisStatus.Processing:
      return "inProgress";
    default:
      return "notFound";
  }
};

const notifyStatusChange = (
  fileId: number,
  status: AiDisplayStatus,
  onStatusChange?: (fileId: number, status: AiDisplayStatus) => void,
) => {
  setCachedDisplayStatus(fileId, status);
  onStatusChange?.(fileId, status);
};

const BulletList = ({ items }: { items: string[] }) => {
  if (items.length === 0) {
    return <Typography variant="body2" color="text.secondary">None identified.</Typography>;
  }
  return (
    <Box component="ul" sx={{ m: 0, pl: 2.5 }}>
      {items.map((item) => (
        <Typography component="li" variant="body2" key={item} sx={{ mb: 0.5 }}>
          {item}
        </Typography>
      ))}
    </Box>
  );
};

const formatPromptVersion = (promptVersion: string | null): string => {
  if (!promptVersion?.trim()) return "—";
  const trimmed = promptVersion.trim();
  return trimmed.startsWith("v") ? trimmed : `v${trimmed}`;
};

const AnalysisMetadata = ({ analysis }: { analysis: DocumentAnalysisDto }) => (
  <Box
    sx={{
      mt: 1,
      pt: 2,
      borderTop: 1,
      borderColor: "divider",
    }}
  >
    <Typography variant="caption" color="text.secondary" sx={{ display: "block" }}>
      Generated By: {analysis.aiModel?.trim() || "—"}
    </Typography>
    <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 0.5 }}>
      Prompt: {formatPromptVersion(analysis.promptVersion)}
    </Typography>
    <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 0.5 }}>
      Processed: {formatProcessedDate(analysis.processedUtc)}
    </Typography>
  </Box>
);

const DocumentAnalysisDialog = ({
  open,
  fileId,
  fileName,
  onClose,
  onStatusChange,
}: DocumentAnalysisDialogProps) => {
  const [analysis, setAnalysis] = useState<DocumentAnalysisDto | null>(null);
  const [viewState, setViewState] = useState<ViewState>("loading");
  const [errorMessage, setErrorMessage] = useState("");
  const [snackbarOpen, setSnackbarOpen] = useState(false);
  const onStatusChangeRef = useRef(onStatusChange);

  useEffect(() => {
    onStatusChangeRef.current = onStatusChange;
  }, [onStatusChange]);

  useEffect(() => {
    if (!open || !fileId) return;

    let cancelled = false;

    setAnalysis(null);
    setViewState("loading");
    setErrorMessage("");
    setSnackbarOpen(false);

    void (async () => {
      try {
        const result = await getAnalysis(fileId);
        if (cancelled) return;

        if (!result) {
          setAnalysis(null);
          setViewState("notFound");
          notifyStatusChange(fileId, "notAnalyzed", onStatusChangeRef.current);
          return;
        }

        setAnalysis(result);
        setViewState(resolveViewState(result));
        notifyStatusChange(fileId, mapAnalysisToDisplayStatus(result), onStatusChangeRef.current);
      } catch {
        if (cancelled) return;
        setErrorMessage("Could not load document analysis.");
        setViewState("error");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [open, fileId]);

  const runAnalysis = async (action: "analyze" | "retry") => {
    setViewState("submitting");
    setErrorMessage("");
    try {
      if (action === "analyze") {
        await analyzeDocument(fileId);
      } else {
        await retryAnalysis(fileId);
      }
      setAnalysis(null);
      setViewState("started");
      notifyStatusChange(fileId, "processing", onStatusChangeRef.current);
    } catch {
      setErrorMessage(
        action === "analyze"
          ? "Document analysis could not be started."
          : "Analysis retry could not be started.",
      );
      setViewState("error");
    }
  };

  const handleCopySummary = async () => {
    const summaryText = analysis?.summary?.trim();
    if (!summaryText) return;

    try {
      await navigator.clipboard.writeText(summaryText);
      setSnackbarOpen(true);
    } catch {
      setErrorMessage("Could not copy summary to clipboard.");
      setViewState("error");
    }
  };

  const renderStatusBanner = () => {
    if (viewState === "inProgress" || viewState === "started") {
      return <Alert severity="warning">Analysis is currently in progress.</Alert>;
    }
    if (viewState === "completed") {
      return <Alert severity="success">Analysis completed successfully.</Alert>;
    }
    return null;
  };

  const renderContent = () => {
    if (viewState === "loading" || viewState === "submitting") {
      return (
        <Stack spacing={2} sx={{ py: 4, alignItems: "center" }}>
          <CircularProgress />
          <Typography variant="body2" color="text.secondary">
            {viewState === "submitting" ? "Starting analysis..." : "Loading analysis..."}
          </Typography>
        </Stack>
      );
    }

    if (viewState === "error") {
      return <Alert severity="error">{errorMessage}</Alert>;
    }

    if (viewState === "notFound") {
      return <Alert severity="info">Document has not been analyzed.</Alert>;
    }

    if (viewState === "started") {
      return (
        <Stack spacing={2}>
          <Alert severity="info">Analysis started successfully.</Alert>
          <Box>
            <Typography variant="body2" color="text.secondary" gutterBottom>
              Status:
            </Typography>
            <Chip
              label={AI_DISPLAY_STATUS_LABELS.processing}
              color={AI_DISPLAY_STATUS_CHIP_COLOR.processing}
              size="small"
            />
          </Box>
          <Alert severity="info">
            This may take a few moments. You can close this dialog and reopen it later to view the results.
          </Alert>
        </Stack>
      );
    }

    if (viewState === "inProgress") {
      return (
        <Stack spacing={2}>
          <Typography variant="body2" color="text.secondary">
            This may take a few moments. You can close this dialog and reopen it later to view the results.
          </Typography>
        </Stack>
      );
    }

    if (viewState === "failed") {
      return (
        <Stack spacing={2}>
          <Alert severity="error">
            Analysis could not be completed. Please retry analysis. If the problem persists, contact support.
          </Alert>
          {analysis?.summary && (
            <Typography variant="body2" color="text.secondary">
              {analysis.summary}
            </Typography>
          )}
          {analysis && <AnalysisMetadata analysis={analysis} />}
        </Stack>
      );
    }

    if (!analysis) return null;

    const summaryText = analysis.summary?.trim() || "";

    return (
      <Stack spacing={3}>
        <Box>
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              gap: 1,
              mb: 1,
            }}
          >
            <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
              Summary
            </Typography>
            {summaryText && (
              <Button
                size="small"
                startIcon={<ContentCopyIcon />}
                onClick={() => void handleCopySummary()}
              >
                Copy Summary
              </Button>
            )}
          </Box>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="body2">
                {summaryText || "No summary available."}
              </Typography>
            </CardContent>
          </Card>
        </Box>

        <Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }} gutterBottom>
            Parties
          </Typography>
          {analysis.parties.length > 0 ? (
            <Stack direction="row" spacing={1} sx={{ flexWrap: "wrap", gap: 1 }}>
              {analysis.parties.map((party) => (
                <Chip key={party} label={party} size="small" />
              ))}
            </Stack>
          ) : (
            <Typography variant="body2" color="text.secondary">None identified.</Typography>
          )}
        </Box>

        <Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }} gutterBottom>
            Important Dates
          </Typography>
          {analysis.importantDates.length > 0 ? (
            <List dense disablePadding>
              {analysis.importantDates.map((date) => (
                <ListItem key={date} disableGutters sx={{ py: 0.25 }}>
                  <Typography variant="body2">{date}</Typography>
                </ListItem>
              ))}
            </List>
          ) : (
            <Typography variant="body2" color="text.secondary">None identified.</Typography>
          )}
        </Box>

        <Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }} gutterBottom>
            Key Findings
          </Typography>
          <BulletList items={analysis.keyPoints} />
        </Box>

        <Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }} gutterBottom>
            Recommended Actions
          </Typography>
          <BulletList items={analysis.nextActions} />
        </Box>

        <AnalysisMetadata analysis={analysis} />
      </Stack>
    );
  };

  return (
    <>
      <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
        <DialogTitle>
          <Typography variant="h6" component="div">
            AI Document Analysis
          </Typography>
          {fileName && (
            <Box sx={{ mt: 0.5 }}>
              <Typography variant="body2" color="text.secondary">
                Document Name
              </Typography>
              <Typography variant="body2" color="text.secondary">
                ({fileName})
              </Typography>
            </Box>
          )}
        </DialogTitle>
        <DialogContent dividers>
          <Stack spacing={2}>
            {renderStatusBanner()}
            {renderContent()}
          </Stack>
        </DialogContent>
        <DialogActions sx={{ px: 3, py: 2 }}>
          {viewState === "notFound" && (
            <Button variant="contained" onClick={() => void runAnalysis("analyze")} sx={{ bgcolor: "#0d1b2a" }}>
              Analyze
            </Button>
          )}
          {viewState === "failed" && (
            <Button variant="contained" onClick={() => void runAnalysis("retry")} sx={{ bgcolor: "#0d1b2a" }}>
              Retry Analysis
            </Button>
          )}
          <Button onClick={onClose}>Close</Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={snackbarOpen}
        autoHideDuration={3000}
        onClose={() => setSnackbarOpen(false)}
        message="Summary copied."
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
      />
    </>
  );
};

export default DocumentAnalysisDialog;
